server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: huawei.franklin3.top
      port: 6379
      password: "@aLZSB666"
      timeout: 50000 # 连接超时时间（毫秒）
      jedis:
        pool: # 连接池配置
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
#  security:

#  security:
#    user:
#      name: admin
#      password: 666666
mybatis:
  type-aliases-package: com.github.franklinthree.main.pojo
  mapper-locations: classpath:com/github/franklinthree/main/mapper/*.xml
logging:
  config: classpath:logback-spring.xml
my:
  api:
    - name: textin
      headers:
      - name: x-ti-app-id
        value: f3af4d38da7e289b4c1a648aeeb401c4
      - name: x-ti-secret-code
        value: 7c41149a4ab5d619b2cddf1986ddd627
